---
title: "FinalProject"
author: "Will Moscato"
date: "4/13/2021"
output: html_document
---

```{r europe top 5 setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r europe top 5 library}
library(tidyverse)
library(tidymodels)
library(lubridate)
library(vip)
library(stacks)
library(DALEX)
library(DALEXtra)
```

```{r europe top 5 prem modeling creation}
fifa19_modeling <- fifa19_modeling %>%
  mutate(Player = paste(Player, '19'))

fifa18_modeling <- fifa18_modeling %>%
  mutate(Player = paste(Player, '18'))

fifa17_modeling <- fifa17_modeling %>%
  mutate(Player = paste(Player, '17'))

prem_modeling <- fifa19_modeling %>%
  rbind(fifa18_modeling) %>%
  rbind(fifa17_modeling) %>%
  mutate(revision = as.factor(revision), Nation = as.factor(Nation),
         league = 'prem')
```

```{r europe top 5 bundesliga modeling creation}
fifa19_modeling_bundesliga2 <- fifa19_modeling_bundesliga %>%
  mutate(Player = paste(Player, '19'))

fifa18_modeling_bundesliga2 <- fifa18_modeling_bundesliga %>%
  mutate(Player = paste(Player, '18'))

fifa17_modeling_bundesliga2 <- fifa17_modeling_bundesliga %>%
  mutate(Player = paste(Player, '17'))



bundesliga_modeling <- fifa17_modeling_bundesliga2%>% 
  bind_rows(fifa18_modeling_bundesliga2, fifa19_modeling_bundesliga2) %>% 
  mutate(revision = as.factor(revision), Nation = as.factor(Nation),
         league = 'bundesliga')
```

```{r europe top 5 la liga modeling creation}
fifa19_modeling_la_liga2 <- fifa19_modeling_la_liga %>%
  mutate(Player = paste(Player, '19'))

fifa18_modeling_la_liga2 <- fifa18_modeling_la_liga %>%
  mutate(Player = paste(Player, '18'))

fifa17_modeling_la_liga2 <- fifa17_modeling_la_liga %>%
  mutate(Player = paste(Player, '17'))



la_liga_modeling <- fifa17_modeling_la_liga2%>% 
  bind_rows(fifa18_modeling_la_liga2, fifa19_modeling_la_liga2) %>%
  select(-Starts) %>%
  mutate(revision = as.factor(revision), Nation = as.factor(Nation),
         league = 'la liga')
```

```{r europe top 5 serie a modeling creation}
fifa19_modeling_serie_a2 <- fifa19_modeling_serie_a %>%
  mutate(Player = paste(Player, '19'))

fifa18_modeling_serie_a2 <- fifa18_modeling_serie_a %>%
  mutate(Player = paste(Player, '18'))

fifa17_modeling_serie_a2 <- fifa17_modeling_serie_a %>%
  mutate(Player = paste(Player, '17'))



serie_a_modeling <- fifa17_modeling_serie_a2%>% 
  bind_rows(fifa18_modeling_serie_a2, fifa19_modeling_serie_a2) %>% 
  mutate(revision = as.factor(revision), Nation = as.factor(Nation),
         league = 'serie a')
```

```{r europe top 5 ligue 1 modeling creation}
fifa19_modeling_ligue12 <- ligue1_fifa19_modeling %>%
  mutate(Player = paste(Player, '19'))

fifa18_modeling_ligue12 <- ligue1_fifa18_modeling %>%
  mutate(Player = paste(Player, '18'))

fifa17_modeling_ligue12 <- ligue1_fifa17_modeling %>%
  mutate(Player = paste(Player, '17'))



ligue1_modeling <- fifa17_modeling_ligue12%>% 
  bind_rows(fifa18_modeling_ligue12, fifa19_modeling_ligue12) %>% 
  mutate(revision = as.factor(revision), Nation = as.factor(Nation),
         league = 'ligue 1')
```

```{r europe top 5 dim check}
dim(ligue1_modeling)
dim(serie_a_modeling)
dim(la_liga_modeling)
dim(prem_modeling)
dim(bundesliga_modeling)
```

```{r europe top 5 all leagues modeling creation}
all_leagues_modeling <- prem_modeling %>%
  rbind(bundesliga_modeling, la_liga_modeling, serie_a_modeling, ligue1_modeling)
```

```{r europe top 5 all modeling outfield creation/cleaning}
'%ni%' <- Negate('%in%')

all_modeling_outfield <- all_leagues_modeling %>% 
  filter(position != "GK") %>% 
  filter(MP > 19) %>%
  mutate(position = ifelse(position == "RWB", "RB", ifelse(position == "LWB", "LB", position))) %>% 
  mutate(position = ifelse(position == 'CF', 'ST', position)) %>%
  mutate(position = as.factor(position)) %>%
  select(-Goals_allowed, -GA90, -SoTA, -Saves, -Save_percent, -W, -L, -D, -CS, -CS_percent, -Pkatt_against, -PKA, -PKsv, -Pk_Save_percent, -PKm, -Born, -G_plus_A_minus_PK_per90, -G_plus_A_per90, -G_per90, -A_per90, -G_minus_Pk_per90, -minutes_played_divided_by90, -Pts)
```

```{r europe top 5 all modeling outfield cleaning cont}
all_modeling_outfield <- all_modeling_outfield %>%
  add_n_miss() %>%
  filter(n_miss_all == 0) %>%
  select(-n_miss_all)
```

```{r europe top 5 splitting/training/testing}
set.seed(494)
all_split <- initial_split(all_modeling_outfield, prop = .75, strata = "revision")
all_training <- training(all_split)
all_testing <- testing(all_split)
```

```{r europe top 5 lasso recipe}
all_lasso_recipe <- recipe(revision ~ . , data = all_training) %>% 
  step_rm(Player, Squad, Nation, league, Attendance) %>%
  step_upsample(revision, over_ratio = .33) %>% 
  step_normalize(all_predictors(),
                 -all_nominal()) %>% 
  step_dummy(all_nominal(),
             -all_outcomes())

all_lasso_recipe %>% 
  prep(all_training) %>% 
  juice()
```

```{r europe top 5 laso WF creation}
all_lasso <- logistic_reg(mixture = 1) %>% 
  set_engine("glmnet") %>% 
  set_args(penalty = tune()) %>% 
  set_mode("classification")

all_lasso_wf <- 
  workflow() %>% 
  add_recipe(all_lasso_recipe) %>% 
  add_model(all_lasso)
```

```{r europe top 5 cv and tune creation}
set.seed(494) # for reproducibility
all_cv <- vfold_cv(all_training, v = 5)

penalty_grid <- grid_regular(penalty(),
                             levels = 10)

all_lasso_tune <- 
  all_lasso_wf %>% 
  tune_grid(
    resamples = all_cv,
    grid = penalty_grid
    )
```

```{r europe top 5 best model lasso}
best <- all_lasso_tune %>% 
  select_best(metric = "accuracy")
```

```{r europe top 5 final wf lasso}
all_lasso_final_wf <- all_lasso_wf %>% 
  finalize_workflow(best)
```

```{r europe top 5 lasso final mod}
all_lasso_final_mod <- all_lasso_final_wf %>% 
  fit(data = all_training)

all_lasso_final_mod %>% 
  pull_workflow_fit() %>% 
  tidy() 
```

```{r europe top 5 lasso vip}
all_lasso_final_mod %>% 
  pull_workflow_fit() %>% 
  vip()
```

```{r europe top 5 lasso testing creation}
all_lasso_test <- all_lasso_final_wf %>% 
  last_fit(all_split)

all_lasso_test %>% 
  collect_metrics()
```

```{r europe top 5 lasso prediction/confusion}
preds <- all_lasso_test %>% 
  collect_predictions()

preds %>% 
  conf_mat(revision, .pred_class)
```

```{r europe top 5 lasso test col bind}
lasso_test <- all_testing %>% 
  bind_cols(predict(all_lasso_final_mod, new_data = all_testing, type = "prob")) %>% 
  bind_cols(predict(all_lasso_final_mod, new_data = all_testing)) 
```

```{r europe top 5 lasso error league check}
lasso_test %>% 
  filter(.pred_class != revision) %>%
  select(Player, revision, .pred_class, position, .pred_TOTS, league) %>%
  group_by(league) %>%
  summarise(total = n()) %>%
  arrange(desc(total))
```

```{r europe top 5 ranger split}
set.seed(494)
all_split <- initial_split(all_modeling_outfield, prop = .75, strata = "revision")
all_training <- training(all_split)
all_testing <- testing(all_split)
```

```{r europe top 5 serieatable1, echo - FALSE}
all_train_metrics <- all_training %>% 
  mutate(Type = "Training") %>% 
  rename(Revision = revision) %>% 
  group_by(Revision, Type) %>% 
  summarize(Goals = mean(Gls, na.rm = T), Assists = mean(Ast, na.rm = T), `Non PK Goals` = mean(Non_PK_G, na.rm = T), PK = mean(PK, na.rm = T), `Team Rank` = mean(Rk, na.rm = T), `Minutes Per 90` = mean(Min, na.rm = T)/90 , `Goals SD` = sd(Gls, na.rm = T), `Assists SD` = sd(Ast, na.rm = T), `Non PK Goals SD` = sd(Non_PK_G, na.rm = T),`Team Rank SD` = sd(Rk, na.rm = T), `Minutes Per 90 SD` = sd(Min, na.rm = T)/90)

all_test_metrics <- all_testing %>% 
  mutate(Type = "Testing") %>% 
  rename(Revision = revision) %>% 
  group_by(Revision, Type) %>% 
  summarize(Goals = mean(Gls, na.rm = T), Assists = mean(Ast, na.rm = T), `Non PK Goals` = mean(Non_PK_G, na.rm = T), PK = mean(PK, na.rm = T),`Team Rank` = mean(Rk, na.rm = T), `Minutes Per 90` = mean(Min, na.rm = T)/90, `Goals SD` = sd(Gls, na.rm = T), `Assists SD` = sd(Ast, na.rm = T), `Non PK Goals SD` = sd(Non_PK_G, na.rm = T),`Team Rank SD` = sd(Rk, na.rm = T), `Minutes Per 90 SD` = sd(Min, na.rm = T)/90)

all_rebound_split <- rbind(all_train_metrics, all_test_metrics) %>% arrange(Revision)

all_metrics_table <- formattable(all_rebound_split[1:4,1:13])

kable(all_metrics_table, align = c(rep('c', 1))) %>% 
  row_spec(0) %>% 
  kable_styling(full_width = F) %>% 
  add_header_above(c("Europe Top Five Leagues Training and Testing Group Comparison for Suspected KPIs" = 13), background = "red", color = "#00FF00")
```

```{r europe top 5 ranger recipe}
all_ranger_recipe <- recipe(revision ~., data = all_training) %>% 
  step_rm(Player, Squad, Nation, Attendance) %>% 
  step_upsample(revision, over_ratio = .33) %>% 
  step_mutate_at(all_numeric(), fn = ~as.numeric(.))

all_ranger_recipe %>% 
  prep(all_training) %>% 
  juice()
```

```{r europe top 5 ranger wf creation}
all_ranger <- rand_forest(mtry = tune(), 
              min_n = tune(), 
              trees = 100) %>% 
  set_mode("classification") %>% 
  set_engine("ranger")

all_ranger_wf <- 
  workflow() %>% 
  add_recipe(all_ranger_recipe) %>% 
  add_model(all_ranger) 
```

```{r europe top 5 ranger cv creation}
set.seed(494)
all_cv <- vfold_cv(all_training, v = 5)

all_rf_grid <- grid_regular(min_n(), finalize(mtry(), all_training %>% select(-revision)), levels = 3)

all_ctrl_res <- control_stack_grid()

all_ranger_cv <- all_ranger_wf %>% 
  tune_grid(resamples = all_cv,
           grid = all_rf_grid,
           control = all_ctrl_res)
```


```{r europe top 5 ranger best and final wf}
all_best1 <- all_ranger_cv %>% 
  select_best(metric = "accuracy")

all_ranger_final_wf<- all_ranger_wf %>% 
  finalize_workflow(all_best1)
```

```{r europe top 5 ranger explainer creation}
all_ranger_fit <- all_ranger_final_wf %>% 
  fit(all_training)


all_rf_explain <- 
  explain_tidymodels(
    model = all_ranger_fit,
    data = all_training %>% select(-revision), 
    y = as.numeric(all_training$revision == "TOTS"),
    label = "rf"
  )
```

```{r europe top 5 ranger vip}
all_rf_var_imp <- 
  model_parts(
    all_rf_explain
    )

plot(all_rf_var_imp)
```


```{r europe top 5 ranger metrics}
all_ranger_test <- all_ranger_final_wf %>% 
  last_fit(all_split)

all_ranger_test %>% 
  collect_metrics()
```

```{r europe top 5 ranger confusion}
all_preds1 <- all_ranger_test %>% 
  collect_predictions()

all_preds1 %>% 
  conf_mat(revision, .pred_class)
```

```{r europe top 5 seriearanger7, echo = FALSE}
all_ranger_test <- all_testing %>% 
  bind_cols(predict(all_ranger_fit, new_data = all_testing, type = "prob")) %>% 
  bind_cols(predict(all_ranger_fit, new_data = all_testing)) 

all_confusion_table <- all_ranger_test %>% 
  conf_mat(revision, .pred_class)

all_ranger_ggconfusion <- autoplot(all_confusion_table, type = "heatmap") + labs(title = "Confusion Matrix of Europe's Top Five Leagues Random Forest Model") + scale_fill_gradient(low = "blue", high = "red") + theme(plot.title = element_text(hjust = .5, size = 15))


all_final_confusion <- ggdraw() + draw_image("https://static.wikia.nocookie.net/logopedia/images/a/a6/UEFA_%281995%29.svg/revision/latest?cb=20180731115352") + 
  draw_plot(all_ranger_ggconfusion)

all_final_confusion 
```

```{r europe top 5 ranger pred col bind}
all_ranger_test <- all_testing %>% 
  bind_cols(predict(all_ranger_fit, new_data = all_testing, type = "prob")) %>% 
  bind_cols(predict(all_ranger_fit, new_data = all_testing)) 
```

```{r europe top 5 ranger error league check}
all_ranger_test %>% 
  filter(.pred_class != revision) %>%
  select(Player, revision, .pred_class, position, .pred_TOTS, league) %>%
  group_by(league) %>%
  summarise(total = n()) %>%
  arrange(desc(total))
```

```{r europe top 5 fifa 21 leagues mutate}
fifa21_modeling <- fifa21_modeling %>%
  select(-Starts) %>%
  mutate(league = 'prem')

fifa21_modeling_bundesliga <- fifa21_modeling_bundesliga %>%
  mutate(league = 'bundesliga')

fifa21_modeling_la_liga <- fifa21_modeling_la_liga %>%
  mutate(league = 'la liga')

fifa21_modeling_ligue1 <- fifa21_modeling_ligue1 %>%
  mutate(league = 'ligue 1')

fifa21_modeling_serie_a <- fifa21_modeling_serie_a %>%
  mutate(league = 'serie a')
```

```{r europe top 5 all modeling 21 creation}
all_modeling21 <- fifa21_modeling_bundesliga %>%
  rbind(fifa21_modeling, fifa21_modeling_la_liga, fifa21_modeling_serie_a, fifa21_modeling_ligue1)
```

```{r europe top 5 all modeling 21 mutate}
all_modeling21 <- all_modeling21 %>% 
  mutate(revision = as.factor(revision), Nation = as.factor(Nation), Age = as.integer(Age))
```

```{r europe top 5 all modeling outfield 21 creation/clean}
all_modeling_outfield21 <- all_modeling21 %>% 
  filter(position != "GK") %>% 
  filter(MP >= 14) %>% 
  mutate(position = ifelse(position == 'CF', 'ST', position)) %>%
  mutate(position = ifelse(position == "RWB", "RB", ifelse(position == "LWB", "LB", position)))
```

```{r europe top 5 ranger 21 preds col bind}
all_ranger_test21 <- all_modeling_outfield21 %>% 
  bind_cols(predict(all_ranger_fit, new_data = all_modeling_outfield21, type = "prob")) %>% 
  bind_cols(predict(all_ranger_fit, new_data = all_modeling_outfield21)) 
```

Premier League TOTS Prediction

```{r europe top 5 prem attackers}
all_ranger_test21 %>%
  filter(league == 'prem') %>%
  #filter(position %in% c('CB', 'RB', 'LB')) %>%
  filter(position %in% c('LW', 'ST', 'RW')) %>%
  #filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

```{r europe top 5 prem mid}
all_ranger_test21 %>%
  filter(league == 'prem') %>%
  #filter(position %in% c('CB', 'RB', 'LB')) %>%
  #filter(position %in% c('LW', 'ST', 'RW')) %>%
  filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

```{r europe top 5 prem def}
all_ranger_test21 %>%
  filter(league == 'prem') %>%
  filter(position %in% c('CB', 'RB', 'LB')) %>%
  #filter(position %in% c('LW', 'ST', 'RW')) %>%
  #filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

La Liga TOTS Prediction

```{r europe top 5 la liga attackers}
all_ranger_test21 %>%
  filter(league == 'la liga') %>%
  #filter(position %in% c('CB', 'RB', 'LB')) %>%
  filter(position %in% c('LW', 'ST', 'RW')) %>%
  #filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

```{r europe top 5 la liga mid}
all_ranger_test21 %>%
  filter(league == 'la liga') %>%
  #filter(position %in% c('CB', 'RB', 'LB')) %>%
  #filter(position %in% c('LW', 'ST', 'RW')) %>%
  filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

```{r europe top 5 la liga def}
all_ranger_test21 %>%
  filter(league == 'la liga') %>%
  filter(position %in% c('CB', 'RB', 'LB')) %>%
  #filter(position %in% c('LW', 'ST', 'RW')) %>%
  #filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

Ligue 1 TOTS Prediction

```{r europe top 5 ligue 1 attackers}
all_ranger_test21 %>%
  filter(league == 'ligue 1') %>%
  #filter(position %in% c('CB', 'RB', 'LB')) %>%
  filter(position %in% c('LW', 'ST', 'RW')) %>%
  #filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

```{r europe top 5 ligue 1 mid}
all_ranger_test21 %>%
  filter(league == 'ligue 1') %>%
  #filter(position %in% c('CB', 'RB', 'LB')) %>%
  #filter(position %in% c('LW', 'ST', 'RW')) %>%
  filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

```{r europe top 5 ligue 1 def}
all_ranger_test21 %>%
  filter(league == 'ligue 1') %>%
  filter(position %in% c('CB', 'RB', 'LB')) %>%
  #filter(position %in% c('LW', 'ST', 'RW')) %>%
  #filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

Bundesliga TOTS Prediction

```{r europe top 5 bundesliga attackers}
all_ranger_test21 %>%
  filter(league == 'bundesliga') %>%
  #filter(position %in% c('CB', 'RB', 'LB')) %>%
  filter(position %in% c('LW', 'ST', 'RW')) %>%
  #filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

```{r europe top 5 bundesliga mid}
all_ranger_test21 %>%
  filter(league == 'bundesliga') %>%
  #filter(position %in% c('CB', 'RB', 'LB')) %>%
  #filter(position %in% c('LW', 'ST', 'RW')) %>%
  filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

```{r europe top 5 bundesliga def}
all_ranger_test21 %>%
  filter(league == 'bundesliga') %>%
  filter(position %in% c('CB', 'RB', 'LB')) %>%
  #filter(position %in% c('LW', 'ST', 'RW')) %>%
  #filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

Serie A TOTS Prediction

```{r europe top 5 serie a attackers}
all_ranger_test21 %>%
  filter(league == 'serie a') %>%
  #filter(position %in% c('CB', 'RB', 'LB')) %>%
  filter(position %in% c('LW', 'ST', 'RW')) %>%
  #filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

```{r europe top 5 serie a mid}
all_ranger_test21 %>%
  filter(league == 'serie a') %>%
  #filter(position %in% c('CB', 'RB', 'LB')) %>%
  #filter(position %in% c('LW', 'ST', 'RW')) %>%
  filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

```{r europe top 5 serie a def}
all_ranger_test21 %>%
  filter(league == 'serie a') %>%
  filter(position %in% c('CB', 'RB', 'LB')) %>%
  #filter(position %in% c('LW', 'ST', 'RW')) %>%
  #filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

Europe's Top Five Leagues TOTS Prediction

```{r europe top 5 TOTY attack}
all_ranger_test21 %>%
  #filter(position %in% c('CB', 'RB', 'LB')) %>%
  filter(position %in% c('LW', 'ST', 'RW')) %>%
  #filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

```{r europe top 5 TOTY mid}
all_ranger_test21 %>%
  #filter(position %in% c('CB', 'RB', 'LB')) %>%
  #filter(position %in% c('LW', 'ST', 'RW')) %>%
  filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```

```{r europe top 5 TOTY def}
all_ranger_test21 %>%
  filter(position %in% c('CB', 'RB', 'LB')) %>%
  #filter(position %in% c('LW', 'ST', 'RW')) %>%
  #filter(position %in% c('LM', 'CM', 'CAM', 'CDM', 'RM')) %>%
  arrange(desc(.pred_TOTS)) %>%
  select(Player, .pred_TOTS) %>%
  head(5)
```
