---
title: "Bundesliga Cleaning"
author: "Will Moscato"
date: "4/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(lubridate)
```


```{r}
fifa17 <- read.csv("fut_bin17_players.csv")
fifa18 <- read.csv("fut_bin18_players.csv")
fifa19 <- read.csv("fut_bin19_players.csv")
bundesliganames17 <- read.csv("16_17_bundesliganames.csv")
bundesliganames18 <- read.csv("17_18_bundesliganames.csv")
bundesliganames19 <- read.csv("18_19_bundesliganames.csv")
standardbundesliga17 <- read.csv("standardbundesliga17.csv")
standardbundesliga18 <- read.csv("standardbundesliga18.csv")
standardbundesliga19 <- read.csv("standardbundesliga19.csv")
bundesligatable17 <- read.csv("bundesligatable17.csv")
bundesligatable18 <- read.csv("bundesligatable18.csv")
bundesligatable19 <- read.csv("bundesligatable19.csv")
goalkeeper_bundesliga17 <- read.csv('goalkeeper_bundesliga17.csv')
goalkeeper_bundesliga18 <- read.csv('goalkeeper_bundesliga18.csv')
goalkeeper_bundesliga19 <- read.csv('goalkeeper_bundesliga19.csv')
```




##17

```{r}
bundesliganames17 <-bundesliganames17 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```


```{r}
bundesliga17_names <- fifa17_names %>% 
  filter(league == "Bundesliga") %>% 
  select(player_name, player_extended_name, overall, revision, position)
```



```{r}
bundesliga17 <- bundesliganames17 %>%
  inner_join(bundesliga17_names, by = c("Player" = "player_extended_name")) %>% 
  select(-Player1, -player_name)
```


```{r}
missing_bundesliga17 <- bundesliganames17 %>%
  left_join(bundesliga17_names, by = c("Player" = "player_extended_name")) %>% 
  filter(is.na(player_name) == TRUE)
```





```{r}
not_missing_bundesliga_17 <- missing_bundesliga17 %>% 
  select(-overall, -revision, -position) %>% 
  left_join(bundesliga17_names, by = c("Player" = "player_name")) 
```


```{r}

last_names_bundesliga17 <- not_missing_bundesliga_17 %>% 
 filter(is.na(overall) == TRUE) %>% 
  mutate(Player_short =  gsub(".* ", "", Player)) %>% 
  mutate(Player_short = ifelse(Player_short == "Alcantara", "Thiago", ifelse(Player_short == "Barkok", "Aymen", ifelse(Player_short == "Harita", "Ben-Harita", ifelse(Player_short == "Blasis", "De Blasis", ifelse(Player_short == "Bracker", "Callsen-Bracker", ifelse(Player_short == "Cleber", "Cleber Reis", ifelse(Player_short =="won", "Ji Dong Won", ifelse(Player_short == "cheol", "Koo Ja Cheol", ifelse(Player_short == "ho", "Park Joo Ho", ifelse(Player_short == "Moting", "Choupo-Moting", ifelse(Player_short == "Engel", "Stroh-Engel", ifelse(Player_short == "Martinez", "Palacios Martinez", ifelse(Player_short == "Guzman", "De Guzman", ifelse(Player_short == "Jong", "De Jong", Player_short))))))))))))))) %>% 
  select(-player_name, -player_extended_name, -overall, -revision, - Player1, -position)

not_real_name_bundesliga17 <- not_missing_bundesliga_17 %>% 
  filter(is.na(overall) == FALSE) %>% 
  select(-Player1, -player_name, -player_extended_name)
```


```{r}
weird_names_bundesliga17 <- last_names_bundesliga17 %>% 
  inner_join(bundesliga17_names, by = c("Player_short" = "player_name")) %>% 
  select(-Player_short, -player_extended_name)
```

```{r}
fifa17_bundesliga_full <- bundesliga17 %>%
  bind_rows(not_real_name_bundesliga17, weird_names_bundesliga17) %>% 
  distinct(Player, .keep_all = TRUE) %>% 
  select(Player, revision, position, Int, TklW, OG, PKcon)
```


```{r}
standardbundesliga17 <- standardbundesliga17 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```

```{r}
fifa17_bundesliga_standard_stats <- fifa17_bundesliga_full %>% 
  inner_join(standardbundesliga17, by = "Player") %>% 
  select(-Player1, -Pos) %>% 
  distinct(Player, .keep_all = TRUE)
```

```{r}
fifa17_standard_plus_table_bundesliga <- fifa17_bundesliga_standard_stats %>% 
  inner_join(bundesligatable17, by = "Squad")
```


```{r}
goalkeeper_bundesliga17 <- goalkeeper_bundesliga17 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) %>% 
  rename(Pkatt_against = PKatt) %>% 
  rename(Goals_allowed = GA) %>%
  select(-X90s, -Pos, -Nation, -Squad, -MP, -Starts, -Min, -Age, -Born)
```

```{r}
fifa17_modeling_bundesliga <- fifa17_standard_plus_table_bundesliga %>% 
  left_join(goalkeeper_bundesliga17, by = "Player") %>% 
  rename(minutes_played_divided_by90 = X90s, Non_PK_G = G.PK, G_plus_A_per90 = G.A, G_minus_Pk_per90 = G.PK.1, G_plus_A_minus_PK_per90 = G.A.PK, Save_percent = Save., CS_percent = CS., Pk_Save_percent = Save..1, G_per90 = Gls.1, A_per90 = Ast.1 ) %>% 
  select(-Matches.x, -Matches.y, -Player1) %>% 
  mutate(Nation = sub('.* ', '', Nation)) 
```




##18


```{r}
bundesliganames18 <-bundesliganames18 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```


```{r}
bundesliga18_names <- fifa18_names %>% 
  filter(league == "Bundesliga") %>% 
  select(player_name, player_extended_name, overall, revision, position)
```



```{r}
bundesliga18 <- bundesliganames18 %>%
  inner_join(bundesliga18_names, by = c("Player" = "player_extended_name")) %>% 
  select(-Player1, -player_name)
```


```{r}
missing_bundesliga18 <- bundesliganames18 %>%
  left_join(bundesliga18_names, by = c("Player" = "player_extended_name")) %>% 
  filter(is.na(player_name) == TRUE)
```





```{r}
not_missing_bundesliga_18 <- missing_bundesliga18 %>% 
  select(-overall, -revision, -position) %>% 
  left_join(bundesliga18_names, by = c("Player" = "player_name")) 
```


```{r}

last_names_bundesliga18 <- not_missing_bundesliga_18 %>% 
   filter(is.na(overall) == TRUE) %>% 
  mutate(Player_short =  gsub(".* ", "", Player)) %>% 
  mutate(Player_short = ifelse(Player_short == "Alcantara", "Thiago", ifelse(Player_short == "Barkok", "Aymen", ifelse(Player_short == "Harita", "Ben-Harita", ifelse(Player_short == "Blasis", "De Blasis", ifelse(Player_short == "Bracker", "Callsen-Bracker", ifelse(Player_short == "Cleber", "Cleber Reis", ifelse(Player_short =="won", "Ji Dong Won", ifelse(Player_short == "cheol", "Koo Ja Cheol", ifelse(Player_short == "ho", "Park Joo Ho", ifelse(Player_short == "Moting", "Choupo-Moting", ifelse(Player_short == "Engel", "Stroh-Engel", ifelse(Player_short == "Martinez", "Palacios Martinez", ifelse(Player_short == "Guzman", "De Guzman", ifelse(Player_short == "Jong", "De Jong", Player_short))))))))))))))) %>% 
  select(-player_name, -player_extended_name, -overall, -revision, - Player1, -position)

not_real_name_bundesliga18 <- not_missing_bundesliga_18 %>% 
  filter(is.na(overall) == FALSE) %>% 
  select(-Player1, -player_name, -player_extended_name)
```


```{r}
weird_names_bundesliga18 <- last_names_bundesliga18 %>% 
  inner_join(bundesliga18_names, by = c("Player_short" = "player_name")) %>% 
  select(-Player_short, -player_extended_name)
```

```{r}
fifa18_bundesliga_full <- bundesliga18 %>%
  bind_rows(not_real_name_bundesliga18, weird_names_bundesliga18) %>% 
  distinct(Player, .keep_all = TRUE) %>% 
  select(Player, revision, position, Int, TklW, OG, PKcon)
```


```{r}
standardbundesliga18 <- standardbundesliga18 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```

```{r}
fifa18_bundesliga_standard_stats <- fifa18_bundesliga_full %>% 
  inner_join(standardbundesliga18, by = "Player") %>% 
  select(-Player1, -Pos) %>% 
  distinct(Player, .keep_all = TRUE)
```

```{r}
fifa18_standard_plus_table_bundesliga <- fifa18_bundesliga_standard_stats %>% 
  inner_join(bundesligatable18, by = "Squad")
```


```{r}
goalkeeper_bundesliga18 <- goalkeeper_bundesliga18 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) %>% 
  rename(Pkatt_against = PKatt) %>% 
  rename(Goals_allowed = GA) %>%
  select(-X90s, -Pos, -Nation, -Squad, -MP, -Starts, -Min, -Age, -Born)
```

```{r}
fifa18_modeling_bundesliga <- fifa18_standard_plus_table_bundesliga %>% 
  left_join(goalkeeper_bundesliga18, by = "Player") %>% 
  rename(minutes_played_divided_by90 = X90s, Non_PK_G = G.PK, G_plus_A_per90 = G.A, G_minus_Pk_per90 = G.PK.1, G_plus_A_minus_PK_per90 = G.A.PK, Save_percent = Save., CS_percent = CS., Pk_Save_percent = Save..1, G_per90 = Gls.1, A_per90 = Ast.1 ) %>% 
  select(-Matches.x, -Matches.y, -Player1, -xG, -npxG, -xA, -npxG.1, -npxG.xA, -npxG.xA.1, -xG.1, -xA.1, -xG.xA) %>% 
  mutate(Nation = sub('.* ', '', Nation))
```


##19
```{r}
bundesliganames19 <-bundesliganames19 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```


```{r}
bundesliga19_names <- fifa19_names %>% 
  filter(league == "Bundesliga") %>% 
  select(player_name, player_extended_name, overall, revision, position)
```



```{r}
bundesliga19 <- bundesliganames19 %>%
  inner_join(bundesliga19_names, by = c("Player" = "player_extended_name")) %>% 
  select(-Player1, -player_name)
```


```{r}
missing_bundesliga19 <- bundesliganames19 %>%
  left_join(bundesliga19_names, by = c("Player" = "player_extended_name")) %>% 
  filter(is.na(player_name) == TRUE)
```





```{r}
not_missing_bundesliga_19 <- missing_bundesliga19 %>% 
  select(-overall, -revision, -position) %>% 
  left_join(bundesliga19_names, by = c("Player" = "player_name")) 
```


```{r}

last_names_bundesliga19 <- not_missing_bundesliga_19 %>% 
  filter(is.na(overall) == TRUE) %>% 
  mutate(Player_short =  gsub(".* ", "", Player)) %>% 
  mutate(Player_short = ifelse(Player_short == "Alcantara", "Thiago", ifelse(Player_short == "Barkok", "Aymen", ifelse(Player_short == "Harita", "Ben-Harita", ifelse(Player_short == "Blasis", "De Blasis", ifelse(Player_short == "Bracker", "Callsen-Bracker", ifelse(Player_short == "Cleber", "Cleber Reis", ifelse(Player_short =="won", "Ji Dong Won", ifelse(Player_short == "cheol", "Koo Ja Cheol", ifelse(Player_short == "ho", "Park Joo Ho", ifelse(Player_short == "Moting", "Choupo-Moting", ifelse(Player_short == "Engel", "Stroh-Engel", ifelse(Player_short == "Martinez", "Palacios Martinez", ifelse(Player_short == "Guzman", "De Guzman", ifelse(Player_short == "Jong", "De Jong", ifelse(Player_short == "NDicka", "Ndicka", Player_short)))))))))))))))) %>% 
  select(-player_name, -player_extended_name, -overall, -revision, - Player1, -position)

not_real_name_bundesliga19 <- not_missing_bundesliga_19 %>% 
  filter(is.na(overall) == FALSE) %>% 
  select(-Player1, -player_name, -player_extended_name)
```


```{r}
weird_names_bundesliga19 <- last_names_bundesliga19 %>% 
  inner_join(bundesliga19_names, by = c("Player_short" = "player_name")) %>% 
  select(-Player_short, -player_extended_name)
```

```{r}
fifa19_bundesliga_full <- bundesliga19 %>%
  bind_rows(not_real_name_bundesliga19, weird_names_bundesliga19) %>% 
  distinct(Player, .keep_all = TRUE) %>% 
  select(Player, revision, position, Int, TklW, OG, PKcon)
```


```{r}
standardbundesliga19 <- standardbundesliga19 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```

```{r}
fifa19_bundesliga_standard_stats <- fifa19_bundesliga_full %>% 
  inner_join(standardbundesliga19, by = "Player") %>% 
  select(-Player1, -Pos) %>% 
  distinct(Player, .keep_all = TRUE)
```

```{r}
fifa19_standard_plus_table_bundesliga <- fifa19_bundesliga_standard_stats %>% 
  inner_join(bundesligatable19, by = "Squad")
```


```{r}
goalkeeper_bundesliga19 <- goalkeeper_bundesliga19 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) %>% 
  rename(Pkatt_against = PKatt) %>% 
  rename(Goals_allowed = GA) %>%
  select(-X90s, -Pos, -Nation, -Squad, -MP, -Starts, -Min, -Age, -Born)
```

```{r}
fifa19_modeling_bundesliga <- fifa19_standard_plus_table_bundesliga %>% 
  left_join(goalkeeper_bundesliga19, by = "Player") %>% 
  rename(minutes_played_divided_by90 = X90s, Non_PK_G = G.PK, G_plus_A_per90 = G.A, G_minus_Pk_per90 = G.PK.1, G_plus_A_minus_PK_per90 = G.A.PK, Save_percent = Save., CS_percent = CS., Pk_Save_percent = Save..1, G_per90 = Gls.1, A_per90 = Ast.1) %>% 
  select(-Matches.x, -Matches.y, -Player1) %>% 
  mutate(Nation = sub('.* ', '', Nation))
```

```{r}
dim(fifa17_modeling_bundesliga)
dim(fifa18_modeling_bundesliga)
dim(fifa19_modeling_bundesliga)
```

```{r}
fifa19_modeling_bundesliga %>% 
  filter(revision == "TOTS")
```


