---
title: "Greenberg_Exploratory"
author: "Jake Greenberg"
date: "4/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(lubridate)
library(vip)
library(stacks)
library(DALEX)
library(DALEXtra)
library(themis)

# CHANGES

library(cowplot)
library(formattable)
library(kableExtra)
```


```{r}
fifa19_modeling2 <- fifa19_modeling %>%
  mutate(Player = paste(Player, '19'))

fifa18_modeling2 <- fifa18_modeling %>%
  mutate(Player = paste(Player, '18'))

fifa17_modeling2 <- fifa17_modeling %>%
  mutate(Player = paste(Player, '17'))



prem_modeling <- fifa17_modeling2 %>% 
  bind_rows(fifa18_modeling2, fifa19_modeling2) %>% 
  mutate(revision = as.factor(revision), Nation = as.factor(Nation))
```

```{r}
prem_modeling %>% 
  select(where(is.numeric)) %>% 
  pivot_longer(cols = everything(),
               names_to = "variable", 
               values_to = "value") %>% 
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30) +
  facet_wrap(vars(variable), 
             scales = "free")
```

```{r}
theme_set(theme_cowplot())
prem_prop <- prem_modeling %>% 
# CHANGES:
  rename(Revision = revision) %>% 
  ggplot(aes(x = Revision, fill = Revision)) +
  geom_bar() +
  scale_fill_manual(values = c("TOTS" = "blue", "Normal" = "gold")) +
  # CHANGES
  labs(x = "Revision", y = "Count", title = "Proportion of Revisions Within Premier League Dataset Selected for TOTS") +
  theme(plot.title = element_text(hjust = .2, size = 13.5)) +
  geom_vline(xintercept = 0, linetype = "dotted") 
prem_prop_logo <- ggdraw() + draw_image("https://www.fifplay.com/img/public/premier-league-2-logo.png", x = .42, y = .23, scale = .25) + 
  draw_plot(prem_prop)

prem_prop_logo
```

```{r}
prem_goals_density <- prem_modeling %>% 
  rename(Revision = revision) %>% 
  ggplot(aes(x = Gls, fill = Revision)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = c("TOTS" = "blue", "Normal" = "gold")) +
  labs(x = "Goals", y = "Density", title = "Density Plot of Goals Scored in Premier League Season by Revision Status", subtitle = "TOTS players tend to score goals more prolifically than their non-selected counterparts") + 
theme(plot.subtitle = element_text(hjust = -.35, size = 11), plot.title = element_text(hjust = .1, size = 13.5))

prem_goals_logo <- ggdraw() + draw_image("https://www.fifplay.com/img/public/premier-league-2-logo.png", x = .42, y = .2, scale = .25) + 
  draw_plot(prem_goals_density)

prem_goals_logo
```

```{r}
prem_tablepos_density <- prem_modeling %>% 
  rename(Revision = revision) %>% 
  ggplot(aes(x = Rk, fill = Revision)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = c("TOTS" = "blue", "Normal" = "gold")) +
  labs(x = "Table Position", y = "Density", title = "Density Plot of Premier League Table Position by Revision Status", subtitle = "Players on winning teams (lower table position) make up a substantial proportion of the Premier League TOTS dataset") + 
theme(plot.subtitle = element_text(hjust = .4, size = 10), plot.title = element_text(hjust = .1, size = 13.5))

prem_tablepos_logo <- ggdraw() + draw_image("https://www.fifplay.com/img/public/premier-league-2-logo.png", x = .42, y = .2, scale = .25) + 
  draw_plot(prem_tablepos_density)

prem_tablepos_logo
```

```{r}
# IS THIS AN INDIVIDUAL OR TEAM RATE STAT OR (Minutes Played Per Contest of the Team or just Minutes Played Per Match Played in by Player)???? Could be different for small sample size players 
prem_mppn_density <- prem_modeling %>% 
  rename(Revision = revision) %>% 
  ggplot(aes(x = minutes_played_divided_by90, fill = Revision)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = c("TOTS" = "blue", "Normal" = "gold")) +
  labs(x = "Total Minutes Played Dived by 90 (Full Games Played)", y = "Density", title = "Density Plot of Minutes Played (Per 90 Minutes) by Revision Status", subtitle = "Players who accrue more minutes per contest ") + 
theme(plot.subtitle = element_text(hjust = .3, size = 10), plot.title = element_text(hjust = .1, size = 13.5))

prem_mppn_logo <- ggdraw() + draw_image("https://www.fifplay.com/img/public/premier-league-2-logo.png", x = .42, y = .2, scale = .25) + 
  draw_plot(prem_mppn_density)

prem_mppn_logo
```

```{r}
prem_positions <- prem_modeling %>% 
  rename(Revision = revision) %>% 
  ggplot(aes(x = position, fill = Revision)) +
  geom_bar(position = "identity") +
  scale_fill_manual(values = c("TOTS" = "blue", "Normal" = "gold")) +
  labs(x = "Position", y = "Count", title = "Positional Breakdown Within Premier League Dataset")

prem_positions_logo <- ggdraw() + draw_image("https://www.fifplay.com/img/public/premier-league-2-logo.png", x = .42, y = .22, scale = .25) + 
  draw_plot(prem_positions)

prem_positions_logo
```


```{r}
prem_modeling_outfield <- prem_modeling %>% 
  filter(position != "GK") %>% 
  #filter(position %in% c("ST", "LW", "RW", "CF", "CAM")) %>% 
  filter(minutes_played_divided_by90 >= 19) %>% 
  mutate(position = ifelse(position == "RWB", "RB", ifelse(position == "LWB", "LB", position))) %>% 
  select(-Goals_allowed, -GA90, -SoTA, -Saves, -Save_percent, -W, -L, -D, -CS, -CS_percent, -Pkatt_against, -PKA, -PKsv, -Pk_Save_percent, -PKm)
```


```{r}
set.seed(494)
prem_split <- initial_split(prem_modeling_outfield, prop = .75, strata = "revision")
prem_training <- training(prem_split)
prem_testing <- testing(prem_split)
```

# Not really sure which KPI to use here, but the formatting is what I am trying to show and the contents can be modified

```{r message = FALSE, warning = FALSE}
prem_train_metrics <- prem_training %>% 
  mutate(Type = "Training") %>% 
  rename(Revision = revision) %>% 
  group_by(Revision, Type) %>% 
  summarize(Goals = mean(Gls, na.rm = T), Assists = mean(Ast, na.rm = T), `Non PK Goals` = mean(Non_PK_G, na.rm = T), PK = mean(PK, na.rm = T), `Team Rank` = mean(Rk, na.rm = T), `Minutes Per 90` = mean(Min, na.rm = T)/90 , `Goals SD` = sd(Gls, na.rm = T), `Assists SD` = sd(Ast, na.rm = T), `Non PK Goals SD` = sd(Non_PK_G, na.rm = T), `PK SD` = sd(PK, na.rm = T),`Team Rank SD` = sd(Rk, na.rm = T), `Minutes Per 90 SD` = sd(Min, na.rm = T)/90)

prem_test_metrics <- prem_testing %>% 
  mutate(Type = "Testing") %>% 
  rename(Revision = revision) %>% 
  group_by(Revision, Type) %>% 
  summarize(Goals = mean(Gls, na.rm = T), Assists = mean(Ast, na.rm = T), `Non PK Goals` = mean(Non_PK_G, na.rm = T), PK = mean(PK, na.rm = T),`Team Rank` = mean(Rk, na.rm = T), `Minutes Per 90` = mean(Min, na.rm = T)/90, `Goals SD` = sd(Gls, na.rm = T), `Assists SD` = sd(Ast, na.rm = T), `Non PK Goals SD` = sd(Non_PK_G, na.rm = T), `PK SD` = sd(PK, na.rm = T),`Team Rank SD` = sd(Rk, na.rm = T), `Minutes Per 90 SD` = sd(Min, na.rm = T)/90)

prem_rebound_split <- rbind(prem_train_metrics, prem_test_metrics) %>% arrange(Revision)

prem_metrics_table <- formattable(prem_rebound_split[1:4,1:14])

kable(prem_metrics_table, align = c(rep('c', 14))) %>% 
  row_spec(0) %>% 
  kable_styling(full_width = F) %>% 
  add_header_above(c("Premier League Training and Testing Group Comparison for KPIs" = 14), background = "purple", color = "white")
```



```{r}
prem_lasso_recipe <- recipe(revision ~ . , data = prem_training) %>% 
  step_rm(Player, Nation, Squad, G_per90, A_per90, minutes_played_divided_by90, Attendance, Born) %>%
  step_upsample(revision, over_ratio = .4) %>% 
  step_normalize(all_predictors(),
                 -all_nominal()) %>% 
  step_dummy(all_nominal(),
             -all_outcomes())

prem_lasso_recipe %>% 
  prep(prem_training) %>% 
  juice()
```



```{r}
prem_lasso <- logistic_reg(mixture = 1) %>% 
  set_engine("glmnet") %>% 
  set_args(penalty = tune()) %>% 
  set_mode("classification")

prem_lasso

prem_lasso_wf <- 
  workflow() %>% 
  add_recipe(prem_lasso_recipe) %>% 
  add_model(prem_lasso)

prem_lasso_wf
```

```{r}
set.seed(494) # for reproducibility
prem_cv <- vfold_cv(prem_training, v = 5)

penalty_grid <- grid_regular(penalty(),
                             levels = 10)

penalty_grid

prem_lasso_tune <- 
  prem_lasso_wf %>% 
  tune_grid(
    resamples = prem_cv,
    grid = penalty_grid
    )

prem_lasso_tune
```

```{r}
prem_lasso_tune %>% 
  show_best(metric = "accuracy")
```

```{r}

prem_best <- prem_lasso_tune %>% 
  select_best(metric = "accuracy")
```

```{r}
prem_lasso_final_wf <- prem_lasso_wf %>% 
  finalize_workflow(prem_best)

prem_lasso_final_wf
```
```{r}
prem_lasso_final_mod <- prem_lasso_final_wf %>% 
  fit(data = prem_training)

prem_lasso_final_mod %>% 
  pull_workflow_fit() %>% 
  tidy() 
```

```{r}
prem_lasso_final_mod %>% 
  pull_workflow_fit() %>% 
  vip()
```


```{r}
prem_lasso_test <- prem_lasso_final_wf %>% 
  last_fit(prem_split)

prem_lasso_test %>% 
  collect_metrics()
```


```{r}
prem_preds <- prem_lasso_test %>% 
  collect_predictions()

prem_preds %>% 
  conf_mat(revision, .pred_class)
```


```{r}
prem_lasso_test <- prem_testing %>% 
  bind_cols(predict(prem_lasso_final_mod, new_data = prem_testing, type = "prob")) %>% 
  bind_cols(predict(prem_lasso_final_mod, new_data = prem_testing)) 
```

```{r}
prem_lasso_test %>% 
  conf_mat(revision, .pred_class)
```

```{r}
prem_lasso_test %>% 
  filter(revision != .pred_class)
```


```{r}
prem_ranger_recipe <- recipe(revision ~., data = prem_training) %>% 
  step_rm(Player, Nation, Squad, G_per90, A_per90, minutes_played_divided_by90, Attendance, Born) %>% 
  step_upsample(revision, over_ratio = .4) %>% 
  step_mutate_at(all_numeric(), fn = ~as.numeric(.))

prem_ranger_recipe %>% 
  prep(prem_training) %>% 
  juice()
```


```{r}
prem_ranger <- rand_forest(mtry = tune(), 
              min_n = tune(), 
              trees = 100) %>% 
  set_mode("classification") %>% 
  set_engine("ranger")

prem_ranger_wf <- 
  workflow() %>% 
  add_recipe(prem_ranger_recipe) %>% 
  add_model(prem_ranger) 

prem_ranger_wf
```


```{r}
set.seed(494)

prem_rf_grid <- grid_regular(min_n(), finalize(mtry(), prem_training %>% select(-revision)), levels = 3)

ctrl_res <- control_stack_grid()

prem_ranger_cv <- prem_ranger_wf %>% 
  tune_grid(resamples = prem_cv,
           grid = prem_rf_grid,
           control = ctrl_res)

collect_metrics(prem_ranger_cv)
```


```{r}
prem_best1 <- prem_ranger_cv %>% 
  select_best(metric = "accuracy")

prem_ranger_final_wf<- prem_ranger_wf %>% 
  finalize_workflow(prem_best1)
```

```{r}
set.seed(494)
prem_ranger_fit <- prem_ranger_final_wf %>% 
  fit(prem_training)


prem_rf_explain <- 
  explain_tidymodels(
    model = prem_ranger_fit,
    data = prem_training %>% select(-revision), 
    y = as.numeric(prem_training$revision == "TOTS"),
    label = "rf"
  )
```

```{r}
prem_rf_var_imp <- 
  model_parts(
    prem_rf_explain
    )

plot(prem_rf_var_imp)
```





```{r}
prem_ranger_test <- prem_ranger_final_wf %>% 
  last_fit(prem_split)

prem_ranger_test %>% 
  collect_metrics()
```

```{r}
prem_preds1 <- prem_ranger_test %>% 
  collect_predictions()

prem_preds1 %>% 
  conf_mat(revision, .pred_class)
```

```{r}
prem_ranger_test <- prem_testing %>% 
  bind_cols(predict(prem_ranger_fit, new_data = prem_testing, type = "prob")) %>% 
  bind_cols(predict(prem_ranger_fit, new_data = prem_testing)) 
```

```{r}
prem_ranger_test %>% 
  conf_mat(revision, .pred_class)
```

```{r}
prem_ranger_test %>% 
  filter(revision != .pred_class)
```




```{r}
prem_modeling21 <- fifa21_modeling %>% 
  mutate(revision = as.factor(revision), Nation = as.factor(Nation), Age = as.integer(Age))
```

```{r}
prem_modeling_outfield21 <- prem_modeling21 %>% 
  filter(position != "GK") %>% 
  #filter(position %in% c("ST", "LW", "RW", "CF", "CAM")) %>% 
  filter(minutes_played_divided_by90 >= 19) %>% 
  mutate(position = ifelse(position == "RWB", "RB", ifelse(position == "LWB", "LB", position)))
```


```{r}
prem_ranger_test21 <- prem_modeling_outfield21 %>% 
  bind_cols(predict(prem_ranger_fit, new_data = prem_modeling_outfield21, type = "prob")) %>% 
  bind_cols(predict(prem_ranger_fit, new_data = prem_modeling_outfield21)) 
```


```{r}
prem_lasso_test21 <- prem_modeling_outfield21 %>% 
  bind_cols(predict(prem_lasso_final_mod, new_data = prem_modeling_outfield21, type = "prob")) %>% 
  bind_cols(predict(prem_lasso_final_mod, new_data = prem_modeling_outfield21)) 
```

