---
title: "Predicting EA Sports FIFA Team of the Season in Europe's Five Leagues"
output: html_document
---

## Table of Contents

---------------------

### Introduction

----------------

### Methods and Materials

-------------------------

### English Premier League

--------------------------

### La Liga (Spain)

-------------------

### French Ligue 1

------------------

### German Bundesliga

---------------------

### Italian Serie A

-------------------





\
\







## Introduction

The video game FIFA, which is developed by Electronic Arts (EA) Sports, has become the most popular sports video game in the world in recent years, largely due to its game mode Ultimate Team. The objective of Ultimate Team is to build the best team possible through both buying and selling players, as well as buying packs of cards similarly to how people buy soccer trading cards in real life. Each player receives ratings in various categories based on their real life abilities, and each of these ratings factor into their overall rating. At the end of each season, EA Sports creates a Team of the Season (TOTS), where they select the best player at each position in each league from that season based on how they performed in real life. The players who receive TOTS cards also receive a boost to their overall rating to reflect their abilities in real life. Although most of their choices for TOTS are understandable, there are some choices that confuse and sometimes anger fans. Along with this, EA has never explained how they make their choices. Through the use of machine learning methods and predictive modeling, we aim to determine which variables are most important when choosing a player for TOTS, as well as predict the Team of the Season for Europe's top five leagues based on this season's statistics.






\
\





## Methods and Materials

**Materials**: We retrieved complete player datasets for FIFA 17, FIFA 18, and FIFA 19 from [here](). We retrieved real life statistics from the 2016-2017, 2017-2018, and 2018-2019 seasons from [fbref.com](https://fbref.com/en/). We did not use data from the 2019-2020 season because COVID-19 caused each season to prematurely end in March of 2020.

**Methods**: 






\
\





## English Premier League





\
\




## La Liga (Spain)





\
\




## French Ligue 1






\
\




## German Bundesliga





\
\





## Italian Serie A











