---
title: "La Liga Cleaning"
author: "Will Moscato"
date: "4/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(lubridate)
```


```{r}
la_liganames17 <- read.csv("16_17_la_liganames.csv")
la_liganames18 <- read.csv("17_18_la_liganames.csv")
la_liganames19 <- read.csv("18_19_la_liganames.csv")
standardla_liga17 <- read.csv("standardla_liga17.csv")
standardla_liga18 <- read.csv("standardla_liga18.csv")
standardla_liga19 <- read.csv("standardla_liga19.csv")
la_ligatable17 <- read.csv("la_ligatable17.csv")
la_ligatable18 <- read.csv("la_ligatable18.csv")
la_ligatable19 <- read.csv("la_ligatable19.csv")
goalkeeper_la_liga17 <- read.csv('goalkeeper_la_liga17.csv')
goalkeeper_la_liga18 <- read.csv('goalkeeper_la_liga18.csv')
goalkeeper_la_liga19 <- read.csv('goalkeeper_la_liga19.csv')
la_liganames21 <- read.csv("20_21_la_liganames.csv")
standardla_liga21 <- read.csv("standardla_liga21.csv")
la_ligatable21 <- read.csv("la_ligatable21.csv")

```




##17

```{r}
la_liganames17 <-la_liganames17 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```


```{r}
la_liga17_names <- fifa17_names %>% 
  filter(league == "LaLiga Santander") %>% 
  select(player_name, player_extended_name, overall, revision, position)
```



```{r}
la_liga17 <- la_liganames17 %>%
  inner_join(la_liga17_names, by = c("Player" = "player_extended_name")) %>% 
  select(-Player1, -player_name)
```


```{r}
missing_la_liga17 <- la_liganames17 %>%
  left_join(la_liga17_names, by = c("Player" = "player_extended_name")) %>% 
  filter(is.na(player_name) == TRUE)
```





```{r}
not_missing_la_liga_17 <- missing_la_liga17 %>% 
  select(-overall, -revision, -position) %>% 
  left_join(la_liga17_names, by = c("Player" = "player_name")) 
```


```{r}

last_names_la_liga17 <- not_missing_la_liga_17 %>% 
 filter(is.na(overall) == TRUE) %>% 
  mutate(Player_short =  gsub(".* ", "", Player)) %>% 
  mutate(Player_short = ifelse(Player_short == "Stegen", "Ter Stegen", ifelse(Player_short == "Sanjurjo", "Oier", ifelse(Player_short == "Berchiche", "Yuri", ifelse(Player_short == "Nzonzi", "N'Zonzi", ifelse(Player_short == "Soriano" , "Bruno", ifelse(Player_short == "Niguez", "Saul", ifelse(Player_short == "Etxebarria", "Benat", ifelse(Player_short == "Nacho", "Nacho Fernandez", ifelse(Player_short == "Ramirez", "Sandro", ifelse(Player == "Yeray Alvarez", "Yeray", ifelse(Player == "Jonny Castro", "Jonny", ifelse(Player_short == "Marcos", "De Marcos", ifelse(Player_short == "Michel", "Michel Maicedo", ifelse(Player_short == "Alexander", "Szymanowski", ifelse(Player == "Alvaro Gonzalez", "Alvaro", ifelse(Player_short == "Cuevas", "De Las Cuevas", ifelse(Player_short == "Carcela", "Carcela-Gonzalez", ifelse(Player_short == "Dehli", "Krohn-Dehli", ifelse(Player_short == "Tomas", "De Tomas", Player_short)))))))))))))))))))) %>% 
  select(-player_name, -player_extended_name, -overall, -revision, - Player1, -position)

not_real_name_la_liga17 <- not_missing_la_liga_17 %>% 
  filter(is.na(overall) == FALSE) %>% 
  select(-Player1, -player_name, -player_extended_name)
```


```{r}
weird_names_la_liga17 <- last_names_la_liga17 %>% 
  inner_join(la_liga17_names, by = c("Player_short" = "player_name")) %>% 
  select(-Player_short, -player_extended_name)
```

```{r}
fifa17_la_liga_full <- la_liga17 %>%
  bind_rows(not_real_name_la_liga17, weird_names_la_liga17) %>% 
  distinct(Player, .keep_all = TRUE) %>% 
  select(Player, revision, position, Int, TklW, OG, PKcon)
```


```{r}
standardla_liga17 <- standardla_liga17 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```

```{r}
fifa17_la_liga_standard_stats <- fifa17_la_liga_full %>% 
  inner_join(standardla_liga17, by = "Player") %>% 
  select(-Player1, -Pos) %>% 
  distinct(Player, .keep_all = TRUE)
```

```{r}
fifa17_standard_plus_table_la_liga <- fifa17_la_liga_standard_stats %>% 
  inner_join(la_ligatable17, by = "Squad")
```


```{r}
goalkeeper_la_liga17 <- goalkeeper_la_liga17 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) %>% 
  rename(Pkatt_against = PKatt) %>% 
  rename(Goals_allowed = GA) %>%
  select(-X90s, -Pos, -Nation, -Squad, -MP, -Starts, -Min, -Age, -Born)
```

```{r}
fifa17_modeling_la_liga <- fifa17_standard_plus_table_la_liga %>% 
  left_join(goalkeeper_la_liga17, by = "Player") %>% 
  rename(minutes_played_divided_by90 = X90s, Non_PK_G = G.PK, G_plus_A_per90 = G.A, G_minus_Pk_per90 = G.PK.1, G_plus_A_minus_PK_per90 = G.A.PK, Save_percent = Save., CS_percent = CS., Pk_Save_percent = Save..1, G_per90 = Gls.1, A_per90 = Ast.1 ) %>% 
  select(-Matches.x, -Matches.y, -Player1) %>% 
  mutate(Nation = sub('.* ', '', Nation)) 
```




##18


```{r}
la_liganames18 <-la_liganames18 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```


```{r}
la_liga18_names <- fifa18_names %>% 
  filter(league == "LaLiga Santander") %>% 
  select(player_name, player_extended_name, overall, revision, position)
```



```{r}
la_liga18 <- la_liganames18 %>%
  inner_join(la_liga18_names, by = c("Player" = "player_extended_name")) %>% 
  select(-Player1, -player_name)
```


```{r}
missing_la_liga18 <- la_liganames18 %>%
  left_join(la_liga18_names, by = c("Player" = "player_extended_name")) %>% 
  filter(is.na(player_name) == TRUE)
```





```{r}
not_missing_la_liga_18 <- missing_la_liga18 %>% 
  select(-overall, -revision, -position) %>% 
  left_join(la_liga18_names, by = c("Player" = "player_name")) 
```


```{r}

last_names_la_liga18 <- not_missing_la_liga_18 %>% 
 filter(is.na(overall) == TRUE) %>% 
  mutate(Player_short =  gsub(".* ", "", Player)) %>% 
  mutate(Player_short = ifelse(Player_short == "Stegen", "Ter Stegen", ifelse(Player_short == "Sanjurjo", "Oier", ifelse(Player_short == "Berchiche", "Yuri", ifelse(Player_short == "Nzonzi", "N'Zonzi", ifelse(Player_short == "Soriano" , "Bruno", ifelse(Player_short == "Niguez", "Saul", ifelse(Player_short == "Etxebarria", "Benat", ifelse(Player_short == "Nacho", "Nacho Fernandez", ifelse(Player_short == "Ramirez", "Sandro", ifelse(Player == "Yeray Alvarez", "Yeray", ifelse(Player == "Jonny Castro", "Jonny", ifelse(Player_short == "Marcos", "De Marcos", ifelse(Player_short == "Michel", "Michel Maicedo", ifelse(Player_short == "Alexander", "Szymanowski", ifelse(Player == "Alvaro Gonzalez", "Alvaro", ifelse(Player_short == "Cuevas", "De Las Cuevas", ifelse(Player_short == "Carcela", "Carcela-Gonzalez", ifelse(Player_short == "Dehli", "Krohn-Dehli", ifelse(Player_short == "Tomas", "De Tomas", Player_short)))))))))))))))))))) %>% 
  select(-player_name, -player_extended_name, -overall, -revision, - Player1, -position)

not_real_name_la_liga18 <- not_missing_la_liga_18 %>% 
  filter(is.na(overall) == FALSE) %>% 
  select(-Player1, -player_name, -player_extended_name)
```


```{r}
weird_names_la_liga18 <- last_names_la_liga18 %>% 
  inner_join(la_liga18_names, by = c("Player_short" = "player_name")) %>% 
  select(-Player_short, -player_extended_name)
```

```{r}
fifa18_la_liga_full <- la_liga18 %>%
  bind_rows(not_real_name_la_liga18, weird_names_la_liga18) %>% 
  distinct(Player, .keep_all = TRUE) %>% 
  select(Player, revision, position, Int, TklW, OG, PKcon)
```


```{r}
standardla_liga18 <- standardla_liga18 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```

```{r}
fifa18_la_liga_standard_stats <- fifa18_la_liga_full %>% 
  inner_join(standardla_liga18, by = "Player") %>% 
  select(-Player1, -Pos) %>% 
  distinct(Player, .keep_all = TRUE)
```

```{r}
fifa18_standard_plus_table_la_liga <- fifa18_la_liga_standard_stats %>% 
  inner_join(la_ligatable18, by = "Squad")
```


```{r}
goalkeeper_la_liga18 <- goalkeeper_la_liga18 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) %>% 
  rename(Pkatt_against = PKatt) %>% 
  rename(Goals_allowed = GA) %>%
  select(-X90s, -Pos, -Nation, -Squad, -MP, -Starts, -Min, -Age, -Born)
```

```{r}
fifa18_modeling_la_liga <- fifa18_standard_plus_table_la_liga %>% 
  left_join(goalkeeper_la_liga18, by = "Player") %>% 
  rename(minutes_played_divided_by90 = X90s, Non_PK_G = G.PK, G_plus_A_per90 = G.A, G_minus_Pk_per90 = G.PK.1, G_plus_A_minus_PK_per90 = G.A.PK, Save_percent = Save., CS_percent = CS., Pk_Save_percent = Save..1, G_per90 = Gls.1, A_per90 = Ast.1 ) %>% 
  select(-Matches.x, -Matches.y, -Player1, -xG, -npxG, -xA, -npxG.1, -npxG.xA, -npxG.xA.1, -xG.1, -xA.1, -xG.xA) %>% 
  mutate(Nation = sub('.* ', '', Nation)) %>% 
  filter(Player != "Luis Hernandez")
```


##19
```{r}
la_liganames19 <-la_liganames19 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```


```{r}
la_liga19_names <- fifa19_names %>% 
  filter(league == "LaLiga Santander") %>% 
  select(player_name, player_extended_name, overall, revision, position)
```



```{r}
la_liga19 <- la_liganames19 %>%
  inner_join(la_liga19_names, by = c("Player" = "player_extended_name")) %>% 
  select(-Player1, -player_name)
```


```{r}
missing_la_liga19 <- la_liganames19 %>%
  left_join(la_liga19_names, by = c("Player" = "player_extended_name")) %>% 
  filter(is.na(player_name) == TRUE)
```





```{r}
not_missing_la_liga_19 <- missing_la_liga19 %>% 
  select(-overall, -revision, -position) %>% 
  left_join(la_liga19_names, by = c("Player" = "player_name")) 
```


```{r}

last_names_la_liga19 <- not_missing_la_liga_19 %>% 
  filter(is.na(overall) == TRUE) %>% 
  mutate(Player_short =  gsub(".* ", "", Player)) %>% 
  mutate(Player_short = ifelse(Player_short == "Stegen", "Ter Stegen", ifelse(Player_short == "Sanjurjo", "Oier", ifelse(Player_short == "Berchiche", "Yuri", ifelse(Player_short == "Nzonzi", "N'Zonzi", ifelse(Player_short == "Soriano" , "Bruno", ifelse(Player_short == "Niguez", "Saul", ifelse(Player_short == "Etxebarria", "Benat", ifelse(Player_short == "Nacho", "Nacho Fernandez", ifelse(Player_short == "Ramirez", "Sandro", ifelse(Player == "Yeray Alvarez", "Yeray", ifelse(Player == "Jonny Castro", "Jonny", ifelse(Player_short == "Marcos", "De Marcos", ifelse(Player_short == "Michel", "Michel Maicedo", ifelse(Player_short == "Alexander", "Szymanowski", ifelse(Player == "Alvaro Gonzalez", "Alvaro", ifelse(Player_short == "Cuevas", "De Las Cuevas", ifelse(Player_short == "Carcela", "Carcela-Gonzalez", ifelse(Player_short == "Dehli", "Krohn-Dehli", ifelse(Player_short == "Tomas", "De Tomas", Player_short)))))))))))))))))))) %>%
  select(-player_name, -player_extended_name, -overall, -revision, - Player1, -position)

not_real_name_la_liga19 <- not_missing_la_liga_19 %>% 
  filter(is.na(overall) == FALSE) %>% 
  select(-Player1, -player_name, -player_extended_name)
```


```{r}
weird_names_la_liga19 <- last_names_la_liga19 %>% 
  inner_join(la_liga19_names, by = c("Player_short" = "player_name")) %>% 
  select(-Player_short, -player_extended_name)
```

```{r}
fifa19_la_liga_full <- la_liga19 %>%
  bind_rows(not_real_name_la_liga19, weird_names_la_liga19) %>% 
  distinct(Player, .keep_all = TRUE) %>% 
  select(Player, revision, position, Int, TklW, OG, PKcon)
```


```{r}
standardla_liga19 <- standardla_liga19 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```

```{r}
fifa19_la_liga_standard_stats <- fifa19_la_liga_full %>% 
  inner_join(standardla_liga19, by = "Player") %>% 
  select(-Player1, -Pos) %>% 
  distinct(Player, .keep_all = TRUE)
```

```{r}
fifa19_standard_plus_table_la_liga <- fifa19_la_liga_standard_stats %>% 
  inner_join(la_ligatable19, by = "Squad")
```


```{r}
goalkeeper_la_liga19 <- goalkeeper_la_liga19 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) %>% 
  rename(Pkatt_against = PKatt) %>% 
  rename(Goals_allowed = GA) %>%
  select(-X90s, -Pos, -Nation, -Squad, -MP, -Starts, -Min, -Age, -Born)
```

```{r}
fifa19_modeling_la_liga <- fifa19_standard_plus_table_la_liga %>% 
  left_join(goalkeeper_la_liga19, by = "Player") %>% 
  rename(minutes_played_divided_by90 = X90s, Non_PK_G = G.PK, G_plus_A_per90 = G.A, G_minus_Pk_per90 = G.PK.1, G_plus_A_minus_PK_per90 = G.A.PK, Save_percent = Save., CS_percent = CS., Pk_Save_percent = Save..1, G_per90 = Gls.1, A_per90 = Ast.1) %>% 
  select(-Matches.x, -Matches.y, -Player1) %>% 
  mutate(Nation = sub('.* ', '', Nation)) %>% 
  filter(Player != "Luis Hernandez") %>% 
  filter(Player != "Mario Suarez")
```

```{r}
dim(fifa17_modeling_la_liga)
dim(fifa18_modeling_la_liga)
dim(fifa19_modeling_la_liga)
```

```{r}
fifa19_modeling_la_liga %>% 
  filter(revision == "TOTS")
```


## 21 testing 

```{r}
la_liganames21 <-la_liganames21 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) 
```


```{r}
la_liga21_names <- fifa21_names %>% 
  filter(league == "LaLiga Santander") %>% 
  select(player_name, player_extended_name, overall, revision, position)
```



```{r}
la_liga21 <- la_liganames21 %>%
  inner_join(la_liga21_names, by = c("Player" = "player_extended_name")) %>% 
  select(-Player1, -player_name)
```


```{r}
missing21 <- la_liganames21 %>%
  left_join(la_liga21_names, by = c("Player" = "player_extended_name")) %>% 
  filter(is.na(player_name) == TRUE)
```





```{r}
not_missing_21 <- missing21 %>% 
  select(-overall, -revision, -position) %>% 
  left_join(la_liga19_names, by = c("Player" = "player_name")) 
```


```{r}

last_names21 <- not_missing_21 %>% 
  filter(is.na(overall) == TRUE) %>% 
  mutate(Player_short =  gsub(".* ", "", Player)) %>% 
 mutate(Player_short = ifelse(Player_short == "Stegen", "Ter Stegen", ifelse(Player_short == "Sanjurjo", "Oier", ifelse(Player_short == "Berchiche", "Yuri", ifelse(Player_short == "Nzonzi", "N'Zonzi", ifelse(Player_short == "Soriano" , "Bruno", ifelse(Player_short == "Niguez", "Saul", ifelse(Player_short == "Etxebarria", "Benat", ifelse(Player_short == "Nacho", "Nacho Fernandez", ifelse(Player_short == "Ramirez", "Sandro", ifelse(Player == "Yeray Alvarez", "Yeray", ifelse(Player == "Jonny Castro", "Jonny", ifelse(Player_short == "Marcos", "De Marcos", ifelse(Player_short == "Michel", "Michel Maicedo", ifelse(Player_short == "Alexander", "Szymanowski", ifelse(Player == "Alvaro Gonzalez", "Alvaro", ifelse(Player_short == "Cuevas", "De Las Cuevas", ifelse(Player_short == "Carcela", "Carcela-Gonzalez", ifelse(Player_short == "Dehli", "Krohn-Dehli", ifelse(Player_short == "Tomas", "De Tomas", Player_short)))))))))))))))))))) %>%
  select(-player_name, -player_extended_name, -overall, -revision, - Player1, -position)

not_real_name21 <- not_missing_21 %>% 
  filter(is.na(overall) == FALSE) %>% 
  select(-Player1, -player_name, -player_extended_name)
```


```{r}
weird_names21 <- last_names21 %>% 
  inner_join(la_liga21_names, by = c("Player_short" = "player_name")) %>% 
  select(-Player_short, -player_extended_name)
```

```{r}
fifa21_la_liga_full <- la_liga21 %>%
  bind_rows(not_real_name21, weird_names21) %>% 
  distinct(Player, .keep_all = TRUE) %>% 
  select(Player, revision, position, Int, TklW, OG, PKcon)
```


```{r}
standardla_liga21 <- standardla_liga21 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) %>% 
  mutate(Age = gsub("-.*", "", Age))
```

```{r}
fifa21_la_liga_standard_stats <- fifa21_la_liga_full %>% 
  inner_join(standardla_liga21, by = "Player") %>% 
  select(-Player1, -Pos) %>% 
  distinct(Player, .keep_all = TRUE)
```

```{r}
fifa21_standard_plus_table_la_liga <- fifa21_la_liga_standard_stats %>% 
  inner_join(la_ligatable21, by = "Squad")
```




```{r}
fifa21_modeling_la_liga <- fifa21_standard_plus_table_la_liga %>% 
   rename(minutes_played_divided_by90 = X90s, Non_PK_G = G.PK, G_plus_A_per90 = G.A, G_minus_Pk_per90 = G.PK.1, G_plus_A_minus_PK_per90 = G.A.PK, G_per90 = Gls.1, A_per90 = Ast.1) %>% 
  mutate(Nation = sub('.* ', '', Nation)) 
```


```{r}
dim(fifa21_modeling)
```
