---
title: "Ligue1Cleaning"
author: "Alexander Denzler"
date: "4/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(lubridate)
```


```{r}
ligue1_names17 <- read.csv("16_17_ligue1names.csv")
ligue1_names18 <- read.csv("17_18_ligue1names.csv")
ligue1_names19 <- read.csv("18_19_ligue1names.csv")
standard_ligue1_17 <- read.csv("standardligue1_17.csv")
standard_ligue1_18 <- read.csv("standardligue1_18.csv")
standard_ligue1_19 <- read.csv("standardligue1_19.csv")
ligue1table17 <- read.csv("ligue1table17.csv")
ligue1table18 <- read.csv("ligue1table18.csv")
ligue1table19 <- read.csv("ligue1table19.csv")
ligue1goalkeeper17 <- read.csv("ligue1goalkeeper17.csv")
ligue1goalkeeper18 <- read.csv("ligue1goalkeeper18.csv")
ligue1goalkeeper19 <- read.csv("ligue1goalkeeper19.csv")
ligue1names21 <- read.csv("20_21_ligue1names.csv")
standardligue121 <- read.csv("standardligue121.csv")
ligue1table21 <- read.csv("ligue1table21.csv")

```


##17

```{r}
ligue1_names17 <-ligue1_names17 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```


```{r}
ligue1_17_names <- fifa17_names %>% 
  filter(league == "Ligue 1") %>% 
  select(player_name, player_extended_name, overall, revision, position)
```



```{r}
ligue1_17 <- ligue1_names17 %>%
  inner_join(ligue1_17_names, by = c("Player" = "player_extended_name")) %>% 
  select(-Player1, -player_name)
```


```{r}
missing_ligue1_17 <- ligue1_names17 %>%
  left_join(ligue1_17_names, by = c("Player" = "player_extended_name")) %>% 
  filter(is.na(player_name) == TRUE)
```





```{r}
not_missing_ligue1_17 <- missing_ligue1_17 %>% 
  select(-overall, -revision, -position) %>% 
  left_join(ligue1_17_names, by = c("Player" = "player_name")) 
```


```{r}
last_names_ligue1_17 <- not_missing_ligue1_17 %>%  
  filter(is.na(overall) == TRUE) %>% 
  mutate(Player_short =  gsub(".* ", "", Player)) %>% 
  mutate(Player_short = ifelse(Player_short == "NDoye", "N'Doye", ifelse(Player_short == "Henrique", "Dalbert", ifelse(Player_short == "Catherine", "Theophile-Catherine", ifelse(Player_short == "Diop", "Issa", ifelse(Player_short == "Maximin", "Saint-Maximin", ifelse(Player_short == "Melou", "Lees-Melou", ifelse(Player_short == "Ekambi", "Toko-Ekambi", ifelse(Player_short == "Moura", "Lucas", ifelse(Player_short == "Paquet", "Monnet-Paquet", ifelse(Player_short == "Nguette", "N'Guette", ifelse(Player_short == "Mbiwa", "Yanga-M'Biwa", ifelse(Player_short == "Preville", "De Preville", ifelse(Player_short == "Assembe", "Ndy Assembe", ifelse(Player_short == "Anguissa", "Zambo Anguissa", ifelse(Player_short == "Lang", "Adam", ifelse(Player_short == "Mbappe", "Mbappe Lottin", ifelse(Player_short == "Ekotto", "Assou-Ekotto", ifelse(Player_short == "Mbengue", "M'Bengue", ifelse(Player_short == "NJie", "N'Jie", ifelse(Player_short == "Ghazi", "El Ghazi", ifelse(Player_short == "Ruf", "Saint-Ruf", ifelse(Player_short == "Bamba", "Abdoulaye", ifelse(Player_short == "Aliadiere", "Jeremie", ifelse(Player_short == "Dolly", "Keagan", ifelse(Player_short == "NDoram", "N'Doram", ifelse(Player_short == "King", "Musavu-King", ifelse(Player_short == "hoon", "Chang-Hoon", Player_short)))))))))))))))))))))))))))) %>% 
  select(-player_name, -player_extended_name, -overall, -revision, - Player1, -position)

not_real_name_ligue1_17 <- not_missing_ligue1_17 %>% 
  filter(is.na(overall) == FALSE) %>% 
  select(-Player1, -player_name, -player_extended_name)
```


```{r}
weird_names_ligue1_17 <- last_names_ligue1_17 %>% 
  inner_join(ligue1_17_names, by = c("Player_short" = "player_name")) %>% 
  select(-Player_short, -player_extended_name)
```

```{r}
fifa17_ligue1_full <- ligue1_17 %>%
  bind_rows(not_real_name_ligue1_17, weird_names_ligue1_17) %>% 
  distinct(Player, .keep_all = TRUE) %>% 
  select(Player, revision, position, Int, TklW, OG, PKcon)
```


```{r}
standard_ligue1_17 <- standard_ligue1_17 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```

```{r}
fifa17_ligue1_standard_stats <- fifa17_ligue1_full %>% 
  inner_join(standard_ligue1_17, by = "Player") %>% 
  select(-Player1, -Pos) %>% 
  distinct(Player, .keep_all = TRUE)
```


```{r}
ligue1table17 <- ligue1table17 %>% 
  select(-MP, -W, -L, -D, -Notes, -Top.Team.Scorer, -Goalkeeper)
```

```{r}
ligue1_fifa17_standard_plus_table <- fifa17_ligue1_standard_stats %>% 
  inner_join(ligue1table17, by = "Squad")
```


```{r}
ligue1goalkeeper17 <- ligue1goalkeeper17 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) %>% 
  rename(Pkatt_against = PKatt) %>% 
  rename(Goals_allowed = GA) %>% 
  select(-X90s, -Pos, -Nation, -Squad, -MP, -Starts, -Min, -Age, -Born, -Rk)
```

```{r}
ligue1_fifa17_modeling <- ligue1_fifa17_standard_plus_table %>% 
  left_join(ligue1goalkeeper17, by = "Player") %>% 
  rename(minutes_played_divided_by90 = X90s, Non_PK_G = G.PK, G_plus_A_per90 = G.A, G_minus_Pk_per90 = G.PK.1, G_plus_A_minus_PK_per90 = G.A.PK, Save_percent = Save., CS_percent = CS., Pk_Save_percent = Save..1, G_per90 = Gls.1, A_per90 = Ast.1 ) %>% 
  select(-Matches.x, -Matches.y, -Player1) %>% 
  mutate(Nation = sub('.* ', '', Nation))
```


##18


```{r}
ligue1_names18 <-ligue1_names18 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```


```{r}
ligue1_18_names <- fifa18_names %>% 
  filter(league == "Ligue 1 Conforama") %>% 
  select(player_name, player_extended_name, overall, revision, position)
```



```{r}
ligue1_18 <- ligue1_names18 %>%
  inner_join(ligue1_18_names, by = c("Player" = "player_extended_name")) %>% 
  select(-Player1, -player_name)
```


```{r}
missing_ligue1_18 <- ligue1_names18 %>%
  left_join(ligue1_18_names, by = c("Player" = "player_extended_name")) %>% 
  filter(is.na(player_name) == TRUE)
```





```{r}
not_missing_ligue1_18 <- missing_ligue1_18 %>% 
  select(-overall, -revision, -position) %>% 
  left_join(ligue1_18_names, by = c("Player" = "player_name")) 
```


```{r}
last_names_ligue1_18 <- not_missing_ligue1_18 %>% 
  filter(is.na(overall) == TRUE) %>% 
  mutate(Player_short =  gsub(".* ", "", Player)) %>% 
  mutate(Player_short = ifelse(Player_short == "Catherine", "Theophile-Catherine", ifelse(Player_short == "Maximin", "Saint-Maximin", ifelse(Player_short == "Melou", "Lees-Melou", ifelse(Player_short == "Ekambi", "Toko-Ekambi", ifelse(Player_short == "Moura", "Lucas", ifelse(Player_short == "Paquet", "Monnet-Paquet", ifelse(Player_short == "Preville", "De Preville", ifelse(Player_short == "Anguissa", "Zambo Anguissa", ifelse(Player_short == "Ekotto", "Assou-Ekotto", ifelse(Player_short == "Mbengue", "M'Bengue", ifelse(Player_short == "NJie", "N'Jie", ifelse(Player_short == "NDoram", "N'Doram", ifelse(Player_short == "hoon", "Chang-Hoon", ifelse(Player_short == "Amian", "Amian Adou", ifelse(Player_short == "Marlon", "Santos", ifelse(Player_short == "Costa", "Da Costa", ifelse(Player_short == "Berchiche", "Yuri", ifelse(Player_short == "MVila", "M'Vila", ifelse(Player_short == "Balde", "Balde Diao", ifelse(Player_short == "jun", "Suk Hyun Jun", ifelse(Player_short == "Gabriel", "Pierre-Gabriel", ifelse(Player_short == "Ngosso", "N'Gosso", ifelse(Player_short == "Adelaide", "Reine-Adelaide", ifelse(Player_short == "Tahrat", "Jean Tahrat", ifelse(Player_short == "Brandon", "Thomas", Player_short)))))))))))))))))))))))))) %>% 
  select(-player_name, -player_extended_name, -overall, -revision, - Player1, -position)

not_real_name_ligue1_18 <- not_missing_ligue1_18 %>% 
  filter(is.na(overall) == FALSE) %>% 
  select(-Player1, -player_name, -player_extended_name)
```


```{r}
weird_names_ligue1_18 <- last_names_ligue1_18 %>% 
  inner_join(ligue1_18_names, by = c("Player_short" = "player_name")) %>% 
  select(-Player_short, -player_extended_name)
```

```{r}
fifa18_ligue1_full <- ligue1_18 %>%
  bind_rows(not_real_name_ligue1_18, weird_names_ligue1_18) %>% 
  distinct(Player, .keep_all = TRUE) %>% 
  select(Player, revision, position, Int, TklW, OG, PKcon)
```


```{r}
standard_ligue1_18 <- standard_ligue1_18 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```

```{r}
fifa18_ligue1_standard_stats <- fifa18_ligue1_full %>% 
  inner_join(standard_ligue1_18, by = "Player") %>% 
  select(-Player1, -Pos, -Rk) %>% 
  distinct(Player, .keep_all = TRUE)
```


```{r}
ligue1table18 <- ligue1table18 %>% 
  select(-MP, -W, -L, -D, -Notes, -Top.Team.Scorer, -Goalkeeper)
```

```{r}
ligue1_fifa18_standard_plus_table <- fifa18_ligue1_standard_stats %>% 
  inner_join(ligue1table18, by = "Squad")
```


```{r}
ligue1goalkeeper18 <- ligue1goalkeeper18 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) %>% 
  rename(Pkatt_against = PKatt) %>% 
  rename(Goals_allowed = GA) %>% 
  select(-X90s, -Pos, -Nation, -Squad, -MP, -Starts, -Min, -Age, -Born, -Rk)
```

```{r}
ligue1_fifa18_modeling <- ligue1_fifa18_standard_plus_table %>%
  left_join(ligue1goalkeeper18, by = "Player") %>% 
  rename(minutes_played_divided_by90 = X90s, Non_PK_G = G.PK, G_plus_A_per90 = G.A, G_minus_Pk_per90 = G.PK.1, G_plus_A_minus_PK_per90 = G.A.PK, Save_percent = Save., CS_percent = CS., Pk_Save_percent = Save..1, G_per90 = Gls.1, A_per90 = Ast.1 ) %>% 
  select(-Matches.x, -Matches.y, -Player1, -xG, -npxG, -xA, -npxG.1, -npxG.xA, -npxG.xA.1, -xG.1, -xA.1, -xG.xA, -Starts) %>% 
  mutate(Nation = sub('.* ', '', Nation))
```


##19
```{r}
ligue1_names19 <- ligue1_names19 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) 
```


```{r}
ligue1_19_names <- fifa19_names %>% 
  filter(league == "Ligue 1 Conforama") %>% 
  select(player_name, player_extended_name, overall, revision, position)
```



```{r}
ligue1_19 <- ligue1_names19 %>%
  inner_join(ligue1_19_names, by = c("Player" = "player_extended_name")) %>% 
  select(-Player1, -player_name)
```


```{r}
missing_ligue1_19 <- ligue1_names19 %>%
  left_join(ligue1_19_names, by = c("Player" = "player_extended_name")) %>% 
  filter(is.na(player_name) == TRUE)
```





```{r}
not_missing_ligue1_19 <- missing_ligue1_19 %>% 
  select(-overall, -revision, -position) %>% 
  left_join(ligue1_19_names, by = c("Player" = "player_name")) 
```


```{r}
last_names_ligue1_19 <- not_missing_ligue1_19 %>% 
  filter(is.na(overall) == TRUE) %>% 
  mutate(Player_short =  gsub(".* ", "", Player)) %>% 
  mutate(Player_short = ifelse(Player_short == "Maximin", "Saint-Maximin", ifelse(Player_short == "Melou", "Lees-Melou", ifelse(Player_short == "Paquet", "Monnet-Paquet", ifelse(Player_short == "Preville", "De Preville", ifelse(Player_short == "NJie", "N'Jie", ifelse(Player_short == "NDoram", "N'Doram", ifelse(Player_short == "hoon", "Chang-Hoon", ifelse(Player_short == "Amian", "Amian Adou", ifelse(Player_short == "Costa", "Da Costa", ifelse(Player_short == "MVila", "M'Vila", ifelse(Player_short == "jun", "Suk Hyun Jun", ifelse(Player_short == "Gabriel", "Pierre-Gabriel", ifelse(Player_short == "Adelaide", "Reine-Adelaide", ifelse(Player_short == "NDoye", "N'Doye", ifelse(Player_short == "Barbosa", "Danilo", ifelse(Player_short == "Car", "Caleta-Car", ifelse(Player_short == "Neymar", "Neymar Jr", ifelse(Player_short == "Martins", "Gelson Martins", ifelse(Player_short == "Fabregas", "Cesc Fabregas", ifelse(Player_short == "Moting", "Choupo-Moting", ifelse(Player_short == "Mbia", "M'Bia", ifelse(Player_short == "Attal", "Atal", Player_short))))))))))))))))))))))) %>%  
  select(-player_name, -player_extended_name, -overall, -revision, - Player1, -position)

not_real_name_ligue1_19 <- not_missing_ligue1_19 %>% 
  filter(is.na(overall) == FALSE) %>% 
  select(-Player1, -player_name, -player_extended_name)
```


```{r}
weird_names_ligue1_19 <- last_names_ligue1_19 %>% 
  inner_join(ligue1_19_names, by = c("Player_short" = "player_name")) %>% 
  select(-Player_short, -player_extended_name)
```

```{r}
fifa19_ligue1_full <- ligue1_19 %>%
  bind_rows(not_real_name_ligue1_19, weird_names_ligue1_19) %>% 
  distinct(Player, .keep_all = TRUE) %>% 
  select(Player, revision, position, Int, TklW, OG, PKcon)
```


```{r}
standard_ligue1_19 <- standard_ligue1_19 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " "))
```

```{r}
fifa19_ligue1_standard_stats <- fifa19_ligue1_full %>% 
  inner_join(standard_ligue1_19, by = "Player") %>% 
  select(-Player1, -Pos, -Rk) %>% 
  distinct(Player, .keep_all = TRUE)
```




```{r}
ligue1_fifa19_standard_plus_table <- fifa19_ligue1_standard_stats %>% 
  inner_join(ligue1table19, by = "Squad") 
```


```{r}
ligue1goalkeeper19 <- ligue1goalkeeper19 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) %>% 
  rename(Pkatt_against = PKatt) %>% 
  rename(Goals_allowed = GA) %>% 
  select(-X90s, -Pos, -Nation, -Squad, -MP, -Starts, -Min, -Age, -Born, -Rk)
```

```{r}
ligue1_fifa19_modeling <- ligue1_fifa19_standard_plus_table %>% 
  left_join(ligue1goalkeeper19, by = "Player") %>% 
 rename(minutes_played_divided_by90 = X90s, Non_PK_G = G.PK, G_plus_A_per90 = G.A, G_minus_Pk_per90 = G.PK.1, G_plus_A_minus_PK_per90 = G.A.PK, Save_percent = Save., CS_percent = CS., Pk_Save_percent = Save..1, G_per90 = Gls.1, A_per90 = Ast.1 ) %>% 
  select(-Matches.x, -Matches.y, -Player1, -xG, -npxG, -xA, -npxG.1, -npxG.xA, -npxG.xA.1, -xG.1, -xA.1, -xG.xA, -Starts) %>% 
  mutate(Nation = sub('.* ', '', Nation))
```

```{r}
dim(ligue1_fifa17_modeling)
dim(ligue1_fifa18_modeling)
dim(ligue1_fifa19_modeling)
```
```{r}
ligue1_fifa19_modeling %>% 
  filter(revision == "TOTS")
```








## 21 testing 

```{r}
ligue1names21 <-ligue1names21 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) 
```


```{r}
ligue121_names <- fifa21_names %>% 
  filter(league == "Ligue 1 Conforama") %>% 
  select(player_name, player_extended_name, overall, revision, position)
```



```{r}
ligue121 <- ligue1names21 %>%
  inner_join(ligue121_names, by = c("Player" = "player_extended_name")) %>% 
  select(-Player1, -player_name)
```


```{r}
missing21 <- ligue1names21 %>%
  left_join(ligue121_names, by = c("Player" = "player_extended_name")) %>% 
  filter(is.na(player_name) == TRUE)
```





```{r}
not_missing_21 <- missing21 %>% 
  select(-overall, -revision, -position) %>% 
  left_join(ligue121_names, by = c("Player" = "player_name")) 
```


```{r}

last_names21 <- not_missing_21 %>% 
  filter(is.na(overall) == TRUE) %>% 
  mutate(Player_short =  gsub(".* ", "", Player)) %>% 
 mutate(Player_short = ifelse(Player_short == "Maximin", "Saint-Maximin", ifelse(Player_short == "Melou", "Lees-Melou", ifelse(Player_short == "Paquet", "Monnet-Paquet", ifelse(Player_short == "Preville", "De Preville", ifelse(Player_short == "NJie", "N'Jie", ifelse(Player_short == "NDoram", "N'Doram", ifelse(Player_short == "hoon", "Chang-Hoon", ifelse(Player_short == "Amian", "Amian Adou", ifelse(Player_short == "Costa", "Da Costa", ifelse(Player_short == "MVila", "M'Vila", ifelse(Player_short == "jun", "Suk Hyun Jun", ifelse(Player_short == "Gabriel", "Pierre-Gabriel", ifelse(Player_short == "Adelaide", "Reine-Adelaide", ifelse(Player_short == "NDoye", "N'Doye", ifelse(Player_short == "Barbosa", "Danilo", ifelse(Player_short == "Car", "Caleta-Car", ifelse(Player_short == "Neymar", "Neymar Jr", ifelse(Player_short == "Martins", "Gelson Martins", ifelse(Player_short == "Fabregas", "Cesc Fabregas", ifelse(Player_short == "Moting", "Choupo-Moting", ifelse(Player_short == "Mbia", "M'Bia", ifelse(Player_short == "Attal", "Atal", Player_short))))))))))))))))))))))) %>%
  select(-player_name, -player_extended_name, -overall, -revision, - Player1, -position)

not_real_name21 <- not_missing_21 %>% 
  filter(is.na(overall) == FALSE) %>% 
  select(-Player1, -player_name, -player_extended_name)
```


```{r}
weird_names21 <- last_names21 %>% 
  inner_join(ligue121_names, by = c("Player_short" = "player_name")) %>% 
  select(-Player_short, -player_extended_name)
```

```{r}
fifa21_ligue1_full <- ligue121 %>%
  bind_rows(not_real_name21, weird_names21) %>% 
  distinct(Player, .keep_all = TRUE) %>% 
  select(Player, revision, position, Int, TklW, OG, PKcon)
```


```{r}
standardligue121 <- standardligue121 %>% 
  mutate(Player1 = gsub(".*\\\\", "", Player)) %>% 
  mutate(Player = str_replace_all(Player1, "-", " ")) %>% 
  mutate(Age = gsub("-.*", "", Age))
```

```{r}
fifa21_ligue1_standard_stats <- fifa21_ligue1_full %>% 
  inner_join(standardligue121, by = "Player") %>% 
  select(-Player1, -Pos) %>% 
  distinct(Player, .keep_all = TRUE)
```

```{r}
fifa21_standard_plus_table_ligue1 <- fifa21_ligue1_standard_stats %>% 
  inner_join(ligue1table21, by = "Squad")
```




```{r}
fifa21_modeling_ligue1 <- fifa21_standard_plus_table_ligue1 %>% 
   rename(minutes_played_divided_by90 = X90s, Non_PK_G = G.PK, G_plus_A_per90 = G.A, G_minus_Pk_per90 = G.PK.1, G_plus_A_minus_PK_per90 = G.A.PK, G_per90 = Gls.1, A_per90 = Ast.1) %>% 
  mutate(Nation = sub('.* ', '', Nation)) 
```


```{r}
dim(fifa21_modeling_ligue1)
```


























