---
title: "Moscato La Liga"
author: "Will Moscato"
date: "4/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(lubridate)
library(vip)
library(stacks)
library(DALEX)
library(DALEXtra)
library(themis)
```


```{r}
fifa19_modeling_la_liga2 <- fifa19_modeling_la_liga %>%
  mutate(Player = paste(Player, '19'))

fifa18_modeling_la_liga2 <- fifa18_modeling_la_liga %>%
  mutate(Player = paste(Player, '18'))

fifa17_modeling_la_liga2 <- fifa17_modeling_la_liga %>%
  mutate(Player = paste(Player, '17'))



la_liga_modeling <- fifa17_modeling_la_liga2%>% 
  bind_rows(fifa18_modeling_la_liga2, fifa19_modeling_la_liga2) %>% 
  select(-Starts) %>% 
  mutate(revision = as.factor(revision), Nation = as.factor(Nation))
```

```{r}
la_liga_modeling %>% 
  select(where(is.numeric)) %>% 
  pivot_longer(cols = everything(),
               names_to = "variable", 
               values_to = "value") %>% 
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30) +
  facet_wrap(vars(variable), 
             scales = "free")
```

```{r}
la_liga_modeling %>% 
  ggplot(aes(x = revision, fill = revision)) +
  geom_bar() +
  scale_fill_manual(values = c("TOTS" = "blue", "Normal" = "gold"))
```



```{r}
la_liga_modeling %>% 
  ggplot(aes(x = Gls, fill = revision)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = c("TOTS" = "blue", "Normal" = "gold")) +
  xlab("Goals")
```

```{r}
la_liga_modeling %>% 
  ggplot(aes(x = Rk, fill = revision)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = c("TOTS" = "blue", "Normal" = "gold")) +
  xlab("Table Position")
```
```{r}
la_liga_modeling %>% 
  ggplot(aes(x = minutes_played_divided_by90, fill = revision)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = c("TOTS" = "blue", "Normal" = "gold")) +
  xlab("Total Minutes Played Dived by 90 (Full Games Played)")
```
```{r}
la_liga_modeling %>% 
  ggplot(aes(x = position, fill = revision)) +
  geom_bar(position = "dodge") +
  scale_fill_manual(values = c("TOTS" = "blue", "Normal" = "gold"))
```


```{r}
la_liga_modeling_outfield <- la_liga_modeling %>% 
  filter(position != "GK") %>% 
  #filter(position %in% c("ST", "LW", "RW", "CF", "CAM")) %>% 
  filter(minutes_played_divided_by90 >= 19) %>% 
  mutate(position = ifelse(position == "RWB", "RB", ifelse(position == "LWB", "LB", ifelse(position == "CF", "ST", position)))) %>% 
  select(-Goals_allowed, -GA90, -SoTA, -Saves, -Save_percent, -W, -L, -D, -CS, -CS_percent, -Pkatt_against, -PKA, -PKsv, -Pk_Save_percent, -PKm)
```


```{r}
set.seed(494)
la_liga_split <- initial_split(la_liga_modeling_outfield, prop = .75, strata = "revision")
la_liga_training <- training(la_liga_split)
la_liga_testing <- testing(la_liga_split)
```



```{r}
la_liga_lasso_recipe <- recipe(revision ~ . , data = la_liga_training) %>% 
  step_rm(Player, Nation, Squad, Born, G_per90, A_per90, minutes_played_divided_by90, Attendance) %>%
  step_upsample(revision, over_ratio = .4) %>% 
  step_normalize(all_predictors(),
                 -all_nominal()) %>% 
  step_dummy(all_nominal(),
             -all_outcomes())

la_liga_lasso_recipe %>% 
  prep(la_liga_training) %>% 
  juice()
```



```{r}
la_liga_lasso <- logistic_reg(mixture = 1) %>% 
  set_engine("glmnet") %>% 
  set_args(penalty = tune()) %>% 
  set_mode("classification")

la_liga_lasso

la_liga_lasso_wf <- 
  workflow() %>% 
  add_recipe(la_liga_lasso_recipe) %>% 
  add_model(la_liga_lasso)

la_liga_lasso_wf
```

```{r}
set.seed(494) # for reproducibility
la_liga_cv <- vfold_cv(la_liga_training, v = 5)

penalty_grid <- grid_regular(penalty(),
                             levels = 10)

penalty_grid

la_liga_lasso_tune <- 
  la_liga_lasso_wf %>% 
  tune_grid(
    resamples = la_liga_cv,
    grid = penalty_grid
    )

la_liga_lasso_tune
```

```{r}
la_liga_lasso_tune %>% 
  show_best(metric = "accuracy")
```

```{r}

la_liga_best <- la_liga_lasso_tune %>% 
  select_best(metric = "accuracy")
```

```{r}
la_liga_lasso_final_wf <- la_liga_lasso_wf %>% 
  finalize_workflow(la_liga_best)

la_liga_lasso_final_wf
```
```{r}
la_liga_lasso_final_mod <- la_liga_lasso_final_wf %>% 
  fit(data = la_liga_training)

la_liga_lasso_final_mod %>% 
  pull_workflow_fit() %>% 
  tidy() 
```

```{r}
la_liga_lasso_final_mod %>% 
  pull_workflow_fit() %>% 
  vip()
```


```{r}
la_liga_lasso_test <- la_liga_lasso_final_wf %>% 
  last_fit(la_liga_split)

la_liga_lasso_test %>% 
  collect_metrics()
```


```{r}
la_liga_preds <- la_liga_lasso_test %>% 
  collect_predictions()

la_liga_preds %>% 
  conf_mat(revision, .pred_class)
```


```{r}
la_liga_lasso_test <- la_liga_testing %>% 
  bind_cols(predict(la_liga_lasso_final_mod, new_data = la_liga_testing, type = "prob")) %>% 
  bind_cols(predict(la_liga_lasso_final_mod, new_data = la_liga_testing)) 
```

```{r}
la_liga_lasso_test %>% 
  conf_mat(revision, .pred_class)
```

```{r}
la_liga_lasso_test %>% 
  filter(revision != .pred_class)
```


```{r}
la_liga_ranger_recipe <- recipe(revision ~., data = la_liga_training) %>% 
  step_rm(Player, Nation, Squad, Born, G_per90, A_per90, minutes_played_divided_by90, OG, Attendance) %>% 
  step_upsample(revision, over_ratio = .5) %>% 
  step_mutate_at(all_numeric(), fn = ~as.numeric(.))

la_liga_ranger_recipe %>% 
  prep(la_liga_training) %>% 
  juice()
```


```{r}
la_liga_ranger <- rand_forest(mtry = tune(), 
              min_n = tune(), 
              trees = 100) %>% 
  set_mode("classification") %>% 
  set_engine("ranger")

la_liga_ranger_wf <- 
  workflow() %>% 
  add_recipe(la_liga_ranger_recipe) %>% 
  add_model(la_liga_ranger) 

la_liga_ranger_wf
```


```{r}
set.seed(494)

la_liga_rf_grid <- grid_regular(min_n(), finalize(mtry(), la_liga_training %>% select(-revision)), levels = 3)

ctrl_res <- control_stack_grid()

la_liga_ranger_cv <- la_liga_ranger_wf %>% 
  tune_grid(resamples = la_liga_cv,
           grid = la_liga_rf_grid,
           control = ctrl_res)

collect_metrics(la_liga_ranger_cv)
```


```{r}
la_liga_best1 <- la_liga_ranger_cv %>% 
  select_best(metric = "accuracy")

la_liga_ranger_final_wf<- la_liga_ranger_wf %>% 
  finalize_workflow(la_liga_best1)
```

```{r}
set.seed(494)
la_liga_ranger_fit <- la_liga_ranger_final_wf %>% 
  fit(la_liga_training)


la_liga_rf_explain <- 
  explain_tidymodels(
    model = la_liga_ranger_fit,
    data = la_liga_training %>% select(-revision), 
    y = as.numeric(la_liga_training$revision == "TOTS"),
    label = "rf"
  )
```

```{r}
la_liga_rf_var_imp <- 
  model_parts(
    la_liga_rf_explain
    )

plot(la_liga_rf_var_imp)
```





```{r}
la_liga_ranger_test <- la_liga_ranger_final_wf %>% 
  last_fit(la_liga_split)

la_liga_ranger_test %>% 
  collect_metrics()
```

```{r}
preds1 <- la_liga_ranger_test %>% 
  collect_predictions()

preds1 %>% 
  conf_mat(revision, .pred_class)
```

```{r}
la_liga_ranger_test <- la_liga_testing %>% 
  bind_cols(predict(la_liga_ranger_fit, new_data = la_liga_testing, type = "prob")) %>% 
  bind_cols(predict(la_liga_ranger_fit, new_data = la_liga_testing)) 
```

```{r}
la_liga_ranger_test %>% 
  conf_mat(revision, .pred_class)
```

```{r}
la_liga_ranger_test %>% 
  filter(revision != .pred_class)
```



```{r}
la_liga_modeling21 <- fifa21_modeling %>% 
  mutate(revision = as.factor(revision), Nation = as.factor(Nation), Age = as.integer(Age))
```

```{r}
la_liga_modeling_outfield21 <- la_liga_modeling21 %>% 
  filter(position != "GK") %>% 
  #filter(position %in% c("ST", "LW", "RW", "CF", "CAM")) %>% 
  filter(minutes_played_divided_by90 >= 19) %>% 
  mutate(position = ifelse(position == "RWB", "RB", ifelse(position == "LWB", "LB", ifelse(position == "CF", "ST", position))))
```


```{r}
la_liga_ranger_test21 <- la_liga_modeling_outfield21 %>% 
  bind_cols(predict(la_liga_ranger_fit, new_data = la_liga_modeling_outfield21, type = "prob")) %>% 
  bind_cols(predict(la_liga_ranger_fit, new_data = la_liga_modeling_outfield21)) 
```


```{r}
la_liga_lasso_test21 <- la_liga_modeling_outfield21 %>% 
  bind_cols(predict(la_liga_lasso_final_mod, new_data = la_liga_modeling_outfield21, type = "prob")) %>% 
  bind_cols(predict(la_liga_lasso_final_mod, new_data = la_liga_modeling_outfield21)) 
```






